"""RepoCiv — Validator module.

Provides explicit validation role for issue completion.
Separated from worker/orchestrator to ensure independent validation.

API:
    validate_issue(repo, issue_id) -> dict with verdict, checks, summary.

Verdicts:
    - "pass"                 — all checks passed, mission can complete.
    - "fail"                 — checks failed, mission cannot complete.
    - "needs-human-review"   — ambiguous, human must decide.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from . import workspace_issue as _wi
from . import repo_config as _rc


def _check_contract_exists(repo: str, issue_id: str) -> dict[str, Any]:
    """Verify a validation contract is present."""
    contract = _wi.read_validation_contract(repo, issue_id)
    if contract is None:
        return {
            "id": "contract-exists",
            "label": "Validation contract exists",
            "passed": False,
            "detail": "No validation_contract.json found",
        }
    return {
        "id": "contract-exists",
        "label": "Validation contract exists",
        "passed": True,
        "detail": f"Contract v{contract.get('version', '?')} present (autoGenerated={contract.get('autoGenerated', False)})",
    }


def _check_spec_present(repo: str, issue_id: str) -> dict[str, Any]:
    """Verify spec.md exists and is non-trivial."""
    spec = _wi.read_spec(repo, issue_id)
    if not spec or len(spec.strip()) < 20:
        return {
            "id": "spec-present",
            "label": "Spec is present and non-trivial",
            "passed": False,
            "detail": "spec.md is missing or too short (< 20 chars)",
        }
    return {
        "id": "spec-present",
        "label": "Spec is present and non-trivial",
        "passed": True,
        "detail": f"spec.md: {len(spec)} chars",
    }


def _check_plan_present(repo: str, issue_id: str) -> dict[str, Any]:
    """Verify plan.md exists and has steps."""
    plan = _wi.read_plan(repo, issue_id)
    if not plan or len(plan.strip()) < 20:
        return {
            "id": "plan-present",
            "label": "Plan is present and non-trivial",
            "passed": False,
            "detail": "plan.md is missing or too short (< 20 chars)",
        }
    return {
        "id": "plan-present",
        "label": "Plan is present and non-trivial",
        "passed": True,
        "detail": f"plan.md: {len(plan)} chars",
    }


def _check_artifacts_exist(repo: str, issue_id: str) -> dict[str, Any]:
    """Verify at least one output artifact was produced."""
    artifacts = _wi.list_artifacts(repo, issue_id)
    if not artifacts:
        return {
            "id": "artifacts-exist",
            "label": "Output artifacts were produced",
            "passed": False,
            "detail": "No artifacts in output/ directory",
        }
    return {
        "id": "artifacts-exist",
        "label": "Output artifacts were produced",
        "passed": True,
        "detail": f"{len(artifacts)} artifact(s): {', '.join(artifacts[:5])}",
    }


def _check_contract_goal_addressed(repo: str, issue_id: str) -> dict[str, Any]:
    """Check that the contract goal is non-empty."""
    contract = _wi.read_validation_contract(repo, issue_id)
    if not contract:
        return {
            "id": "contract-goal",
            "label": "Contract has a goal",
            "passed": False,
            "detail": "No contract to check",
        }
    goal = contract.get("goal", "")
    if not goal.strip():
        return {
            "id": "contract-goal",
            "label": "Contract has a goal",
            "passed": False,
            "detail": "Contract goal is empty",
        }
    return {
        "id": "contract-goal",
        "label": "Contract has a goal",
        "passed": True,
        "detail": f"Goal: {goal[:100]}",
    }


def _check_must_pass_checks(repo: str, issue_id: str) -> list[dict[str, Any]]:
    """Run the mustPassChecks from the validation contract.

    Supported checks:
    - "tests-pass"  — run pytest in the repo directory.
    - "lint-clean"  — run ruff/flake8 if configured.
    - "build-clean" — run the build command from repo config.
    """
    contract = _wi.read_validation_contract(repo, issue_id)
    if not contract:
        return []

    checks = contract.get("mustPassChecks", [])
    results: list[dict[str, Any]] = []

    for check_id in checks:
        if check_id == "tests-pass":
            results.append(_run_tests_check(repo, issue_id))
        elif check_id == "lint-clean":
            results.append(_run_lint_check(repo, issue_id))
        elif check_id == "build-clean":
            results.append(_run_build_check(repo, issue_id))
        else:
            results.append({
                "id": f"must-pass-{check_id}",
                "label": f"Must-pass check: {check_id}",
                "passed": False,
                "detail": f"Unknown check type: {check_id}",
            })

    return results


def _run_tests_check(repo: str, issue_id: str) -> dict[str, Any]:
    """Run pytest in the repo directory. Best-effort."""
    try:
        cfg = _rc.load_repo_config(repo)
        repo_path = Path(cfg.get("path", "."))
        if not repo_path.exists():
            return {
                "id": "tests-pass",
                "label": "Tests pass",
                "passed": False,
                "detail": f"Repo path not found: {repo_path}",
            }
        result = subprocess.run(
            ["python3", "-m", "pytest", "-q", "--tb=short"],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            return {
                "id": "tests-pass",
                "label": "Tests pass",
                "passed": True,
                "detail": result.stdout.strip()[-200:] if result.stdout.strip() else "All tests passed",
            }
        return {
            "id": "tests-pass",
            "label": "Tests pass",
            "passed": False,
            "detail": result.stdout.strip()[-300:] or result.stderr.strip()[-300:] or "Tests failed",
        }
    except subprocess.TimeoutExpired:
        return {
            "id": "tests-pass",
            "label": "Tests pass",
            "passed": False,
            "detail": "pytest timed out (120s)",
        }
    except FileNotFoundError:
        return {
            "id": "tests-pass",
            "label": "Tests pass",
            "passed": True,
            "detail": "pytest not installed, skipping",
        }
    except Exception as e:
        return {
            "id": "tests-pass",
            "label": "Tests pass",
            "passed": False,
            "detail": f"Error running tests: {e}",
        }


def _run_lint_check(repo: str, issue_id: str) -> dict[str, Any]:
    """Run ruff or flake8. Best-effort."""
    try:
        cfg = _rc.load_repo_config(repo)
        repo_path = Path(cfg.get("path", "."))
        if not repo_path.exists():
            return {
                "id": "lint-clean",
                "label": "Lint is clean",
                "passed": False,
                "detail": f"Repo path not found: {repo_path}",
            }
        # Try ruff first, then flake8
        for cmd in [["ruff", "check", "."], ["flake8", "."]]:
            try:
                result = subprocess.run(
                    cmd, cwd=str(repo_path),
                    capture_output=True, text=True, timeout=60,
                )
                if result.returncode == 0:
                    return {
                        "id": "lint-clean",
                        "label": "Lint is clean",
                        "passed": True,
                        "detail": f"{' '.join(cmd)} passed",
                    }
                return {
                    "id": "lint-clean",
                    "label": "Lint is clean",
                    "passed": False,
                    "detail": result.stdout.strip()[-200:] or result.stderr.strip()[-200:],
                }
            except FileNotFoundError:
                continue
        return {
            "id": "lint-clean",
            "label": "Lint is clean",
            "passed": True,
            "detail": "No linter found (ruff/flake8), skipping",
        }
    except Exception as e:
        return {
            "id": "lint-clean",
            "label": "Lint is clean",
            "passed": False,
            "detail": f"Error running lint: {e}",
        }


def _run_build_check(repo: str, issue_id: str) -> dict[str, Any]:
    """Run build command from repo config. Best-effort."""
    try:
        cfg = _rc.load_repo_config(repo)
        build_cmd = cfg.get("buildCommand")
        if not build_cmd:
            return {
                "id": "build-clean",
                "label": "Build is clean",
                "passed": True,
                "detail": "No buildCommand configured, skipping",
            }
        repo_path = Path(cfg.get("path", "."))
        result = subprocess.run(
            build_cmd, shell=True, cwd=str(repo_path),
            capture_output=True, text=True, timeout=120,
        )
        if result.returncode == 0:
            return {
                "id": "build-clean",
                "label": "Build is clean",
                "passed": True,
                "detail": f"Build succeeded: {build_cmd}",
            }
        return {
            "id": "build-clean",
            "label": "Build is clean",
            "passed": False,
            "detail": result.stderr.strip()[-300:] or result.stdout.strip()[-300:] or f"Build failed: {build_cmd}",
        }
    except subprocess.TimeoutExpired:
        return {
            "id": "build-clean",
            "label": "Build is clean",
            "passed": False,
            "detail": "Build timed out (120s)",
        }
    except Exception as e:
        return {
            "id": "build-clean",
            "label": "Build is clean",
            "passed": False,
            "detail": f"Error running build: {e}",
        }


def validate_issue(repo: str, issue_id: str) -> dict[str, Any]:
    """Validate an issue workspace against its validation contract.

    Returns a dict with:
        - verdict: "pass" | "fail" | "needs-human-review"
        - technical_checks: list of {id, label, passed, detail}
        - behaviour_checks: list of {id, label, passed, detail}
        - summary: human-readable summary string
        - evidence: list of evidence strings
        - followups: list of recommended follow-up actions
    """
    technical_checks: list[dict[str, Any]] = []
    behaviour_checks: list[dict[str, Any]] = []
    evidence: list[str] = []
    followups: list[str] = []

    # ── Structural checks (always run) ──────────────────────────────────────
    structural = [
        _check_contract_exists(repo, issue_id),
        _check_spec_present(repo, issue_id),
        _check_plan_present(repo, issue_id),
        _check_artifacts_exist(repo, issue_id),
        _check_contract_goal_addressed(repo, issue_id),
    ]
    technical_checks.extend(structural)

    # ── Contract-driven checks ──────────────────────────────────────────────
    must_pass = _check_must_pass_checks(repo, issue_id)
    technical_checks.extend(must_pass)

    # ── Determine verdict ───────────────────────────────────────────────────
    critical_checks = [c for c in technical_checks if c["id"] in (
        "contract-exists", "spec-present",
    )]
    critical_failures = [c for c in critical_checks if not c["passed"]]

    all_passed = all(c["passed"] for c in technical_checks)
    any_failed = any(not c["passed"] for c in technical_checks)
    must_pass_failures = [c for c in must_pass if not c["passed"]]

    # Determine if contract is auto-generated with minimal content
    contract = _wi.read_validation_contract(repo, issue_id)
    auto_gen_minimal = (
        contract is not None
        and contract.get("autoGenerated", False)
        and not contract.get("goal", "").strip()
    )

    if critical_failures:
        verdict = "fail"
        summary = f"Critical checks failed: {', '.join(c['label'] for c in critical_failures)}"
        followups.append("Fix critical issues and re-run validation")
    elif must_pass_failures:
        verdict = "fail"
        summary = f"Must-pass checks failed: {', '.join(c['label'] for c in must_pass_failures)}"
        followups.append("Fix failing checks listed in validation contract")
    elif auto_gen_minimal:
        # Auto-generated contract with minimal content: be lenient on non-critical
        verdict = "pass"
        summary = "Validation passed (auto-generated contract with minimal content)"
    elif any_failed:
        verdict = "needs-human-review"
        failed_labels = [c["label"] for c in technical_checks if not c["passed"]]
        summary = f"Some checks failed (non-critical): {', '.join(failed_labels)}"
        followups.append("Review failed checks and decide whether to accept or fix")
    else:
        verdict = "pass"
        summary = "All validation checks passed"
        evidence.append(f"{len(technical_checks)} checks passed")

    # Collect evidence from passed checks
    for check in technical_checks:
        if check["passed"]:
            evidence.append(f"[PASS] {check['label']}: {check['detail']}")
        else:
            evidence.append(f"[FAIL] {check['label']}: {check['detail']}")

    return {
        "verdict": verdict,
        "technical_checks": technical_checks,
        "behaviour_checks": behaviour_checks,
        "summary": summary,
        "evidence": evidence,
        "followups": followups,
    }
